"""add_ai_columns_to_media_evidence

Revision ID: cb5272ceaca5
Revises: 007
Create Date: 2026-03-02 00:45:28.396765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb5272ceaca5'
down_revision: Union[str, None] = '007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_audit_created_at'), table_name='audit')
    op.drop_index(op.f('ix_audit_facility_shift_date'), table_name='audit')
    op.create_index(op.f('ix_audit_created_by'), 'audit', ['created_by'], unique=False)
    op.alter_column('audit_checkpoint', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_audit_cp_cat_acp_id'), table_name='audit_checkpoint_category')
    op.drop_index(op.f('ix_audit_cp_cat_is_completed'), table_name='audit_checkpoint_category')
    op.create_index(op.f('ix_audit_checkpoint_category_audit_checkpoint_id'), 'audit_checkpoint_category', ['audit_checkpoint_id'], unique=False)
    op.alter_column('auth_session', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('category', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_category_facility_id'), 'category', ['facility_id'], unique=False)
    op.alter_column('checkpoint', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('checkpoint', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('checkpoint_facility_id_fkey'), 'checkpoint', type_='foreignkey')
    op.create_foreign_key(None, 'checkpoint', 'facility', ['facility_id'], ['id'], ondelete='CASCADE')
    op.alter_column('country', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('country', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_country_code'), table_name='country')
    op.create_unique_constraint(None, 'country', ['code'])
    op.alter_column('facility', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('facility', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('media_evidence', sa.Column('ai_status', sa.String(length=30), server_default='PENDING', nullable=False))
    op.add_column('media_evidence', sa.Column('ai_compliant', sa.Boolean(), nullable=True))
    op.add_column('media_evidence', sa.Column('ai_confidence', sa.Float(), nullable=True))
    op.add_column('media_evidence', sa.Column('ai_observations', sa.Text(), nullable=True))
    op.add_column('media_evidence', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('media_evidence', sa.Column('ai_analyzed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('media_evidence', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shift_config', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shift_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('staff', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('staff', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_unique_constraint(None, 'user', ['email'])
    op.alter_column('zone', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('zone', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zone', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('zone', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('staff', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('staff', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('shift_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('shift_config', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('media_evidence', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('media_evidence', 'ai_analyzed_at')
    op.drop_column('media_evidence', 'ai_summary')
    op.drop_column('media_evidence', 'ai_observations')
    op.drop_column('media_evidence', 'ai_confidence')
    op.drop_column('media_evidence', 'ai_compliant')
    op.drop_column('media_evidence', 'ai_status')
    op.alter_column('facility', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('facility', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'country', type_='unique')
    op.create_index(op.f('ix_country_code'), 'country', ['code'], unique=True)
    op.alter_column('country', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('country', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'checkpoint', type_='foreignkey')
    op.create_foreign_key(op.f('checkpoint_facility_id_fkey'), 'checkpoint', 'facility', ['facility_id'], ['id'])
    op.alter_column('checkpoint', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('checkpoint', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_category_facility_id'), table_name='category')
    op.alter_column('category', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('auth_session', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_audit_checkpoint_category_audit_checkpoint_id'), table_name='audit_checkpoint_category')
    op.create_index(op.f('ix_audit_cp_cat_is_completed'), 'audit_checkpoint_category', ['is_completed'], unique=False)
    op.create_index(op.f('ix_audit_cp_cat_acp_id'), 'audit_checkpoint_category', ['audit_checkpoint_id'], unique=False)
    op.alter_column('audit_checkpoint', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_audit_created_by'), table_name='audit')
    op.create_index(op.f('ix_audit_facility_shift_date'), 'audit', ['facility_id', 'shift_type', 'shift_date'], unique=False)
    op.create_index(op.f('ix_audit_created_at'), 'audit', ['created_at'], unique=False)
    op.alter_column('audit', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
